name: CI (tests)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: |
        until yarn install --frozen-lockfile; do echo "Looks like we've run out of yarns"; done

    - name: Linting check
      run: yarn lint

    - name: Prettier check
      run: yarn format

    - name: TS check
      run: yarn typecheck
      
